# 服务端口号
server:
  port: 8081
  address: 0.0.0.0
  servlet:
    session:
      timeout: 18000
# 数据库地址
datasource:
  url: 47.111.168.145:3306/gcxl

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: gcxl
    password: ruanjunxi.7826
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.example.gcxl.domain
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml
logging:
  level:
    com.example.gcxl.mapper: debug
pagehelper:
  helper-dialect: Mysql
  reasonable: true
  support-methods-arguments: true